Add “No communication” card
Euregan/aperoweb pull request #38
Opened 2020-01-03 14:59 UTC by Cykelero

Fixes #37

2020-01-03 16:59 UTC, zyhou requested changes
Can you rebase?

2020-01-03 16:59 UTC, zyhou commented on pages/index.js
> +    return (
This component is useless now. You can directly add this in `<Home />` component
ie
```js
<h2>Communication</h2>
    <Grid>
         <NextTweet />
         <NoCommunication />
    </Grid>
```

2020-01-03 16:59 UTC, zyhou commented on pages/index.js
> +                        <li key="{plannedTalk.name}">{plannedTalk.name}</li>
```suggestion
                        <li key={plannedTalk.name}>{plannedTalk.name}</li>
```

2020-01-07 14:58 UTC, Euregan commented
#### 📝Changed routes:


| [**/**](https://aperoweb-git-add-no-communication.euregan.now.sh/) |
|:-:|
|<a href="https://aperoweb-git-add-no-communication.euregan.now.sh/"><img src="https://images.weserv.nl?url=https://microlink.nyc3.digitaloceanspaces.com/YpT0_oCYQpT4vfl5qKaBjYxg81g_&w=600" alt="Screenshot of /" width="300"></a><br /><sup><a href="https://images.weserv.nl?url=https://microlink.nyc3.digitaloceanspaces.com/jRb4hfK3VfH_y55cHynJggA2v5w_">(view full size)</a> |







Commit 88e18cc51b7274aa3968206f963242cb7f657286 (https://aperoweb-git-add-no-communication.euregan.now.sh).

2020-01-07 14:58 UTC, Cykelero commented
I've applied the changes you suggested; we should still check that the code works as expected, though.

2020-01-07 14:59 UTC, zyhou submitted a review, later dismissed

2020-01-07 15:14 UTC, Cykelero commented
The branch is now rebased on top of the latest mater commits.

2020-01-11 21:50 UTC, zyhou approved these changes

2020-01-11 21:50 UTC, merged