Add CardWithNetwork
Euregan/aperoweb pull request #41
Opened 2020-01-11 18:59 UTC by Cykelero

Adds the `CardWithNetwork` component, that encapsulates the logic of displaying loading/failure states.
Also adds the `ifLoaded` function to the return object of useDataApi.

It's still not the right abstraction: while the component handles the loading state of the Card chrome, you still need to conditionally generate the card contents base on network status yourself (hence `ifLoaded`).
Same goes for configuring the Card (e.g. its `state` prop)

2020-01-11 19:04 UTC, Euregan commented
#### 📝Changed routes:


| [**/**](https://aperoweb-git-add-network-card.euregan.now.sh/) |
|:-:|
|<a href="https://aperoweb-git-add-network-card.euregan.now.sh/"><img src="https://images.weserv.nl?url=https://microlink.nyc3.digitaloceanspaces.com/WPSz8FJyBmrrI3LhiZRpj1GziYc_&w=600" alt="Screenshot of /" width="300"></a><br /><sup><a href="https://images.weserv.nl?url=https://microlink.nyc3.digitaloceanspaces.com/FmSM_FG3fiuiJ4k0omjPP_onH_4_">(view full size)</a> |







Commit 2ac5c9c711390d4057ab0db1ef74cb2ec19560da (https://aperoweb-git-add-network-card.euregan.now.sh).

2020-01-11 21:54 UTC, zyhou requested changes

2020-01-11 21:54 UTC, zyhou commented on components/Card.js
> +// CardWithNetwork
For me the comment are useless in this case (same above)

2020-01-11 21:54 UTC, zyhou commented on lib/useDataApi.js
> +    });
```
if (!state.isLoading && !state.isError) {
  return produceCallback();
}
return null;
```

2020-01-11 21:54 UTC, zyhou commented on lib/useDataApi.js
> +    });
`else` is useless when you return in the condition

2020-01-11 21:54 UTC, zyhou commented
I like other stuff and your `ifLoaded` :)

2020-01-14 10:32 UTC, zyhou submitted a review, later dismissed

2020-01-14 10:33 UTC, Cykelero commented
😄 thanks!

2020-01-14 10:34 UTC, zyhou commented
Just need rebase and I merge it :)

2020-01-14 10:36 UTC, Cykelero commented
Yep—although I'll need to add some code now, to also change the new NoCommunication component to use CardWithNetwork.

2020-01-27 15:56 UTC, Cykelero commented
Alright! The PR has been rebased on top of master, and updated with `NoCommunication` changes. It should be good to go, now.

2020-01-27 15:56 UTC, zyhou commented on pages/index.js
> +    const nextTweet = requestState.data.nextTweet;
```suggestion
    const { nextTweet }  = requestState.data;
```

Bu it's ok like this :)

2020-01-27 15:56 UTC, zyhou commented on pages/index.js
> +    const plannedTalks = requestState.data.plannedTalks;
same, it's ok too

2020-01-27 15:59 UTC, zyhou approved these changes

2020-01-27 15:59 UTC, merged

2020-01-27 16:01 UTC, Cykelero commented
👍
I had this same thought, and ultimately decided than although using destructuring could help with maintaining consistency with other network calls, here it'd be better to use the natural approach.
We can always change that later!